/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type GetScoresResponseData =
  | ElasticDashAPI.GetScoresResponseData.Numeric
  | ElasticDashAPI.GetScoresResponseData.Categorical
  | ElasticDashAPI.GetScoresResponseData.Boolean;

export namespace GetScoresResponseData {
  export interface Numeric extends ElasticDashAPI.GetScoresResponseDataNumeric {
    dataType: "NUMERIC";
  }

  export interface Categorical
    extends ElasticDashAPI.GetScoresResponseDataCategorical {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ElasticDashAPI.GetScoresResponseDataBoolean {
    dataType: "BOOLEAN";
  }
}
