/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface GetScoresResponseDataCategorical
  extends ElasticDashAPI.CategoricalScore {
  trace?: ElasticDashAPI.GetScoresResponseTraceData;
}
