/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface GetScoresResponse {
  data: ElasticDashAPI.GetScoresResponseData[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
