/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface GetScoresResponseDataNumeric
  extends ElasticDashAPI.NumericScore {
  trace?: ElasticDashAPI.GetScoresResponseTraceData;
}
