/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetAnnotationQueueItemsRequest {
  /** Filter by status */
  status?: ElasticDashAPI.AnnotationQueueStatus;
  /** page number, starts at 1 */
  page?: number;
  /** limit of items per page */
  limit?: number;
}
