/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface AnnotationQueueItem {
  id: string;
  queueId: string;
  objectId: string;
  objectType: ElasticDashAPI.AnnotationQueueObjectType;
  status: ElasticDashAPI.AnnotationQueueStatus;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}
