/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface CreateAnnotationQueueItemRequest {
  objectId: string;
  objectType: ElasticDashAPI.AnnotationQueueObjectType;
  /** Defaults to PENDING for new queue items */
  status?: ElasticDashAPI.AnnotationQueueStatus;
}
