/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface ScimUser {
  schemas: string[];
  id: string;
  userName: string;
  name: ElasticDashAPI.ScimName;
  emails: ElasticDashAPI.ScimEmail[];
  meta: ElasticDashAPI.UserMeta;
}
