/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface ServiceProviderConfig {
  schemas: string[];
  documentationUri: string;
  patch: ElasticDashAPI.ScimFeatureSupport;
  bulk: ElasticDashAPI.BulkConfig;
  filter: ElasticDashAPI.FilterConfig;
  changePassword: ElasticDashAPI.ScimFeatureSupport;
  sort: ElasticDashAPI.ScimFeatureSupport;
  etag: ElasticDashAPI.ScimFeatureSupport;
  authenticationSchemes: ElasticDashAPI.AuthenticationScheme[];
  meta: ElasticDashAPI.ResourceMeta;
}
