/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface BlobStorageIntegrationResponse {
  id: string;
  projectId: string;
  type: ElasticDashAPI.BlobStorageIntegrationType;
  bucketName: string;
  endpoint?: string;
  region: string;
  accessKeyId?: string;
  prefix: string;
  exportFrequency: ElasticDashAPI.BlobStorageExportFrequency;
  enabled: boolean;
  forcePathStyle: boolean;
  fileType: ElasticDashAPI.BlobStorageIntegrationFileType;
  exportMode: ElasticDashAPI.BlobStorageExportMode;
  exportStartDate?: string;
  nextSyncAt?: string;
  lastSyncAt?: string;
  createdAt: string;
  updatedAt: string;
}
