/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

/**
 * Collection of spans from a single instrumentation scope
 */
export interface OtelScopeSpan {
  /** Instrumentation scope information */
  scope?: ElasticDashAPI.OtelScope;
  /** Array of spans */
  spans?: ElasticDashAPI.OtelSpan[];
}
