/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

/**
 * Represents a collection of spans from a single resource as per OTLP specification
 */
export interface OtelResourceSpan {
  /** Resource information */
  resource?: ElasticDashAPI.OtelResource;
  /** Array of scope spans */
  scopeSpans?: ElasticDashAPI.OtelScopeSpan[];
}
