/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface CreateScoreConfigRequest {
  name: string;
  dataType: ElasticDashAPI.ScoreConfigDataType;
  /** Configure custom categories for categorical scores. Pass a list of objects with `label` and `value` properties. Categories are autogenerated for boolean configs and cannot be passed */
  categories?: ElasticDashAPI.ConfigCategory[];
  /** Configure a minimum value for numerical scores. If not set, the minimum value defaults to -∞ */
  minValue?: number;
  /** Configure a maximum value for numerical scores. If not set, the maximum value defaults to +∞ */
  maxValue?: number;
  /** Description is shown across the ElasticDash UI and can be used to e.g. explain the config categories in detail, why a numeric range was set, or provide additional context on config name or usage */
  description?: string;
}
