/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface ScoreConfigs {
  data: ElasticDashAPI.ScoreConfig[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
