/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface PaginatedModels {
  data: ElasticDashAPI.Model[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
