/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface CategoricalScoreV1 extends ElasticDashAPI.BaseScoreV1 {
  /** Represents the numeric category mapping of the stringValue. If no config is linked, defaults to 0. */
  value: number;
  /** The string representation of the score value. If no config is linked, can be any string. Otherwise, must map to a config category */
  stringValue: string;
}
