/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface DatasetRunWithItems extends ElasticDashAPI.DatasetRun {
  datasetRunItems: ElasticDashAPI.DatasetRunItem[];
}
