/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface NumericScore extends ElasticDashAPI.BaseScore {
  /** The numeric value of the score */
  value: number;
}
