/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface NumericScoreV1 extends ElasticDashAPI.BaseScoreV1 {
  /** The numeric value of the score */
  value: number;
}
