/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type ScoreV1 =
  /**
   * Score with NUMERIC data type */
  | ElasticDashAPI.ScoreV1.Numeric
  /**
   * Score with CATEGORICAL data type */
  | ElasticDashAPI.ScoreV1.Categorical
  /**
   * Score with BOOLEAN data type */
  | ElasticDashAPI.ScoreV1.Boolean;

export namespace ScoreV1 {
  export interface Numeric extends ElasticDashAPI.NumericScoreV1 {
    dataType: "NUMERIC";
  }

  export interface Categorical extends ElasticDashAPI.CategoricalScoreV1 {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ElasticDashAPI.BooleanScoreV1 {
    dataType: "BOOLEAN";
  }
}
