/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type Score =
  /**
   * Score with NUMERIC data type */
  | ElasticDashAPI.Score.Numeric
  /**
   * Score with CATEGORICAL data type */
  | ElasticDashAPI.Score.Categorical
  /**
   * Score with BOOLEAN data type */
  | ElasticDashAPI.Score.Boolean;

export namespace Score {
  export interface Numeric extends ElasticDashAPI.NumericScore {
    dataType: "NUMERIC";
  }

  export interface Categorical extends ElasticDashAPI.CategoricalScore {
    dataType: "CATEGORICAL";
  }

  export interface Boolean extends ElasticDashAPI.BooleanScore {
    dataType: "BOOLEAN";
  }
}
