/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface TraceWithFullDetails extends ElasticDashAPI.Trace {
  /** Path of trace in ElasticDash UI */
  htmlPath: string;
  /** Latency of trace in seconds */
  latency?: number | null;
  /** Cost of trace in USD */
  totalCost?: number | null;
  /** List of observations */
  observations: ElasticDashAPI.ObservationsView[];
  /** List of scores */
  scores: ElasticDashAPI.ScoreV1[];
}
