/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface TraceWithDetails extends ElasticDashAPI.Trace {
  /** Path of trace in ElasticDash UI */
  htmlPath: string;
  /** Latency of trace in seconds */
  latency?: number | null;
  /** Cost of trace in USD */
  totalCost?: number | null;
  /** List of observation ids */
  observations?: string[] | null;
  /** List of score ids */
  scores?: string[] | null;
}
