/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface Project {
  id: string;
  name: string;
  /** The organization this project belongs to */
  organization: ElasticDashAPI.Organization;
  /** Metadata for the project */
  metadata: Record<string, unknown>;
  /** Number of days to retain data. Null or 0 means no retention. Omitted if no retention is configured. */
  retentionDays?: number;
}
