/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type ChatMessageWithPlaceholders =
  | ElasticDashAPI.ChatMessageWithPlaceholders.Chatmessage
  | ElasticDashAPI.ChatMessageWithPlaceholders.Placeholder;

export namespace ChatMessageWithPlaceholders {
  export interface Chatmessage extends ElasticDashAPI.ChatMessage {
    type: "chatmessage";
  }

  export interface Placeholder extends ElasticDashAPI.PlaceholderMessage {
    type: "placeholder";
  }
}
