/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type CreatePromptRequest =
  | ElasticDashAPI.CreatePromptRequest.Chat
  | ElasticDashAPI.CreatePromptRequest.Text;

export namespace CreatePromptRequest {
  export interface Chat extends ElasticDashAPI.CreateChatPromptRequest {
    type: "chat";
  }

  export interface Text extends ElasticDashAPI.CreateTextPromptRequest {
    type: "text";
  }
}
