/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type Prompt = ElasticDashAPI.Prompt.Chat | ElasticDashAPI.Prompt.Text;

export namespace Prompt {
  export interface Chat extends ElasticDashAPI.ChatPrompt {
    type: "chat";
  }

  export interface Text extends ElasticDashAPI.TextPrompt {
    type: "text";
  }
}
