/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface CreateGenerationEvent extends ElasticDashAPI.BaseEvent {
  body: ElasticDashAPI.CreateGenerationBody;
}
