/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface CreateGenerationBody extends ElasticDashAPI.CreateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, ElasticDashAPI.MapValue>;
  usage?: ElasticDashAPI.IngestionUsage;
  usageDetails?: ElasticDashAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptName?: string;
  promptVersion?: number;
}
