/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface IngestionResponse {
  successes: ElasticDashAPI.IngestionSuccess[];
  errors: ElasticDashAPI.IngestionError[];
}
