/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type IngestionUsage = ElasticDashAPI.Usage | ElasticDashAPI.OpenAiUsage;
