/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type IngestionEvent =
  /**
   * Creates a new trace. Upserts on id for updates if trace with id exists. */
  | ElasticDashAPI.IngestionEvent.TraceCreate
  /**
   * Creates a new score. Upserts on id for updates if score with id exists. */
  | ElasticDashAPI.IngestionEvent.ScoreCreate
  /**
   * Creates a new span. */
  | ElasticDashAPI.IngestionEvent.SpanCreate
  /**
   * Updates span based on id. */
  | ElasticDashAPI.IngestionEvent.SpanUpdate
  /**
   * Creates a new generation. */
  | ElasticDashAPI.IngestionEvent.GenerationCreate
  /**
   * Updates a generation based on id. */
  | ElasticDashAPI.IngestionEvent.GenerationUpdate
  /**
   * Creates an event. */
  | ElasticDashAPI.IngestionEvent.EventCreate
  /**
   * ElasticDash SDKs only, used for debugging purposes. */
  | ElasticDashAPI.IngestionEvent.SdkLog
  /**
   * Deprecated event type */
  | ElasticDashAPI.IngestionEvent.ObservationCreate
  /**
   * Deprecated event type */
  | ElasticDashAPI.IngestionEvent.ObservationUpdate;

export namespace IngestionEvent {
  export interface TraceCreate extends ElasticDashAPI.TraceEvent {
    type: "trace-create";
  }

  export interface ScoreCreate extends ElasticDashAPI.ScoreEvent {
    type: "score-create";
  }

  export interface SpanCreate extends ElasticDashAPI.CreateSpanEvent {
    type: "span-create";
  }

  export interface SpanUpdate extends ElasticDashAPI.UpdateSpanEvent {
    type: "span-update";
  }

  export interface GenerationCreate
    extends ElasticDashAPI.CreateGenerationEvent {
    type: "generation-create";
  }

  export interface GenerationUpdate
    extends ElasticDashAPI.UpdateGenerationEvent {
    type: "generation-update";
  }

  export interface EventCreate extends ElasticDashAPI.CreateEventEvent {
    type: "event-create";
  }

  export interface SdkLog extends ElasticDashAPI.SdkLogEvent {
    type: "sdk-log";
  }

  export interface ObservationCreate
    extends ElasticDashAPI.CreateObservationEvent {
    type: "observation-create";
  }

  export interface ObservationUpdate
    extends ElasticDashAPI.UpdateObservationEvent {
    type: "observation-update";
  }
}
