/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface UpdateGenerationBody extends ElasticDashAPI.UpdateSpanBody {
  completionStartTime?: string;
  model?: string;
  modelParameters?: Record<string, ElasticDashAPI.MapValue>;
  usage?: ElasticDashAPI.IngestionUsage;
  promptName?: string;
  usageDetails?: ElasticDashAPI.UsageDetails;
  costDetails?: Record<string, number>;
  promptVersion?: number;
}
