/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export type UsageDetails =
  | Record<string, number>
  | ElasticDashAPI.OpenAiCompletionUsageSchema
  | ElasticDashAPI.OpenAiResponseUsageSchema;
