/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface GetCommentsResponse {
  data: ElasticDashAPI.Comment[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
