/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface PaginatedDatasetItems {
  data: ElasticDashAPI.DatasetItem[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
