/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface Observations {
  data: ElasticDashAPI.Observation[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
