/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElasticDashAPI from "../../../index.js";

export interface ObservationsViews {
  data: ElasticDashAPI.ObservationsView[];
  meta: ElasticDashAPI.utils.MetaResponse;
}
