/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core/index.js";
import * as ElasticDashAPI from "../../../index.js";
import {
  mergeHeaders,
  mergeOnlyDefinedHeaders,
} from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Projects {
  export interface Options {
    environment: core.Supplier<string>;
    /** Specify a custom URL to connect the client to. */
    baseUrl?: core.Supplier<string>;
    username?: core.Supplier<string | undefined>;
    password?: core.Supplier<string | undefined>;
    /** Override the X-ElasticDash-Sdk-Name header */
    xElasticDashSdkName?: core.Supplier<string | undefined>;
    /** Override the X-ElasticDash-Sdk-Version header */
    xElasticDashSdkVersion?: core.Supplier<string | undefined>;
    /** Override the X-ElasticDash-Public-Key header */
    xElasticDashPublicKey?: core.Supplier<string | undefined>;
    /** Additional headers to include in requests. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }

  export interface RequestOptions {
    /** The maximum time to wait for a response in seconds. */
    timeoutInSeconds?: number;
    /** The number of times to retry the request. Defaults to 2. */
    maxRetries?: number;
    /** A hook to abort the request. */
    abortSignal?: AbortSignal;
    /** Override the X-ElasticDash-Sdk-Name header */
    xElasticDashSdkName?: string | undefined;
    /** Override the X-ElasticDash-Sdk-Version header */
    xElasticDashSdkVersion?: string | undefined;
    /** Override the X-ElasticDash-Public-Key header */
    xElasticDashPublicKey?: string | undefined;
    /** Additional query string parameters to include in the request. */
    queryParams?: Record<string, unknown>;
    /** Additional headers to include in the request. */
    headers?: Record<
      string,
      string | core.Supplier<string | null | undefined> | null | undefined
    >;
  }
}

export class Projects {
  protected readonly _options: Projects.Options;

  constructor(_options: Projects.Options) {
    this._options = _options;
  }

  /**
   * Get Project associated with API key (requires project-scoped API key). You can use GET /api/public/organizations/projects to get all projects with an organization-scoped key.
   *
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.get()
   */
  public get(
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.Projects> {
    return core.HttpResponsePromise.fromPromise(this.__get(requestOptions));
  }

  private async __get(
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.Projects>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/projects",
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.Projects,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/projects.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Create a new project (requires organization-scoped API key)
   *
   * @param {ElasticDashAPI.CreateProjectRequest} request
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.create({
   *         name: "name",
   *         metadata: undefined,
   *         retention: 1
   *     })
   */
  public create(
    request: ElasticDashAPI.CreateProjectRequest,
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.Project> {
    return core.HttpResponsePromise.fromPromise(
      this.__create(request, requestOptions),
    );
  }

  private async __create(
    request: ElasticDashAPI.CreateProjectRequest,
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.Project>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        "/api/public/projects",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.Project,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/projects.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Update a project by ID (requires organization-scoped API key).
   *
   * @param {string} projectId
   * @param {ElasticDashAPI.UpdateProjectRequest} request
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.update("projectId", {
   *         name: "name",
   *         metadata: undefined,
   *         retention: undefined
   *     })
   */
  public update(
    projectId: string,
    request: ElasticDashAPI.UpdateProjectRequest,
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.Project> {
    return core.HttpResponsePromise.fromPromise(
      this.__update(projectId, request, requestOptions),
    );
  }

  private async __update(
    projectId: string,
    request: ElasticDashAPI.UpdateProjectRequest,
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.Project>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/projects/${encodeURIComponent(projectId)}`,
      ),
      method: "PUT",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.Project,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling PUT /api/public/projects/{projectId}.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete a project by ID (requires organization-scoped API key). Project deletion is processed asynchronously.
   *
   * @param {string} projectId
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.delete("projectId")
   */
  public delete(
    projectId: string,
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.ProjectDeletionResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__delete(projectId, requestOptions),
    );
  }

  private async __delete(
    projectId: string,
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.ProjectDeletionResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/projects/${encodeURIComponent(projectId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.ProjectDeletionResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/projects/{projectId}.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Get all API keys for a project (requires organization-scoped API key)
   *
   * @param {string} projectId
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.getApiKeys("projectId")
   */
  public getApiKeys(
    projectId: string,
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.ApiKeyList> {
    return core.HttpResponsePromise.fromPromise(
      this.__getApiKeys(projectId, requestOptions),
    );
  }

  private async __getApiKeys(
    projectId: string,
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.ApiKeyList>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/projects/${encodeURIComponent(projectId)}/apiKeys`,
      ),
      method: "GET",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.ApiKeyList,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling GET /api/public/projects/{projectId}/apiKeys.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Create a new API key for a project (requires organization-scoped API key)
   *
   * @param {string} projectId
   * @param {ElasticDashAPI.CreateApiKeyRequest} request
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.createApiKey("projectId", {
   *         note: undefined,
   *         publicKey: undefined,
   *         secretKey: undefined
   *     })
   */
  public createApiKey(
    projectId: string,
    request: ElasticDashAPI.CreateApiKeyRequest = {},
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.ApiKeyResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__createApiKey(projectId, request, requestOptions),
    );
  }

  private async __createApiKey(
    projectId: string,
    request: ElasticDashAPI.CreateApiKeyRequest = {},
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.ApiKeyResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/projects/${encodeURIComponent(projectId)}/apiKeys`,
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryParameters: requestOptions?.queryParams,
      requestType: "json",
      body: request,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.ApiKeyResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling POST /api/public/projects/{projectId}/apiKeys.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  /**
   * Delete an API key for a project (requires organization-scoped API key)
   *
   * @param {string} projectId
   * @param {string} apiKeyId
   * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link ElasticDashAPI.Error}
   * @throws {@link ElasticDashAPI.UnauthorizedError}
   * @throws {@link ElasticDashAPI.AccessDeniedError}
   * @throws {@link ElasticDashAPI.MethodNotAllowedError}
   * @throws {@link ElasticDashAPI.NotFoundError}
   *
   * @example
   *     await client.projects.deleteApiKey("projectId", "apiKeyId")
   */
  public deleteApiKey(
    projectId: string,
    apiKeyId: string,
    requestOptions?: Projects.RequestOptions,
  ): core.HttpResponsePromise<ElasticDashAPI.ApiKeyDeletionResponse> {
    return core.HttpResponsePromise.fromPromise(
      this.__deleteApiKey(projectId, apiKeyId, requestOptions),
    );
  }

  private async __deleteApiKey(
    projectId: string,
    apiKeyId: string,
    requestOptions?: Projects.RequestOptions,
  ): Promise<core.WithRawResponse<ElasticDashAPI.ApiKeyDeletionResponse>> {
    let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        Authorization: await this._getAuthorizationHeader(),
        "X-ElasticDash-Sdk-Name":
          requestOptions?.xElasticDashSdkName ??
          this._options?.xElasticDashSdkName,
        "X-ElasticDash-Sdk-Version":
          requestOptions?.xElasticDashSdkVersion ??
          this._options?.xElasticDashSdkVersion,
        "X-ElasticDash-Public-Key":
          requestOptions?.xElasticDashPublicKey ??
          this._options?.xElasticDashPublicKey,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)),
        `/api/public/projects/${encodeURIComponent(projectId)}/apiKeys/${encodeURIComponent(apiKeyId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryParameters: requestOptions?.queryParams,
      timeoutMs:
        requestOptions?.timeoutInSeconds != null
          ? requestOptions.timeoutInSeconds * 1000
          : 60000,
      maxRetries: requestOptions?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
    });
    if (_response.ok) {
      return {
        data: _response.body as ElasticDashAPI.ApiKeyDeletionResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new ElasticDashAPI.Error(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 401:
          throw new ElasticDashAPI.UnauthorizedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 403:
          throw new ElasticDashAPI.AccessDeniedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 405:
          throw new ElasticDashAPI.MethodNotAllowedError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        case 404:
          throw new ElasticDashAPI.NotFoundError(
            _response.error.body as unknown,
            _response.rawResponse,
          );
        default:
          throw new errors.ElasticDashAPIError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    switch (_response.error.reason) {
      case "non-json":
        throw new errors.ElasticDashAPIError({
          statusCode: _response.error.statusCode,
          body: _response.error.rawBody,
          rawResponse: _response.rawResponse,
        });
      case "timeout":
        throw new errors.ElasticDashAPITimeoutError(
          "Timeout exceeded when calling DELETE /api/public/projects/{projectId}/apiKeys/{apiKeyId}.",
        );
      case "unknown":
        throw new errors.ElasticDashAPIError({
          message: _response.error.errorMessage,
          rawResponse: _response.rawResponse,
        });
    }
  }

  protected async _getAuthorizationHeader(): Promise<string | undefined> {
    const username = await core.Supplier.get(this._options.username);
    const password = await core.Supplier.get(this._options.password);
    if (username != null && password != null) {
      return core.BasicAuth.toAuthorizationHeader({
        username: username,
        password: password,
      });
    }

    return undefined;
  }
}
